require 'cucumber/rake/task'
require 'rspec/core/rake_task'

Cucumber::Rake::Task.new(:cucumber) do |task|
  task.cucumber_opts = ['--tags ~@wip']
end

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = './spec/**/*_spec.rb'
  t.rspec_opts = %w(--format documentation --color)
end

task :default => [:spec, :cucumber]